#!/usr/bin/php
<?php

require('vendor/autoload.php');

use \JustCoded\DotenvSync\DotenvDiff;

$argv = $_SERVER['argv'];

switch(count($argv))
{
	case 0 || 1:
		$dotenvSync = new DotenvDiff();
		break;
	case 3:
		$dotenvSync = new DotenvDiff($argv[1], $argv[2]);
		break;
}

echo $dotenvDiff->diff()->output();

exit($dotenvSync->isSuccess() ? 0 : 1);

