#!/usr/bin/php
<?php

require('vendor/autoload.php');

use \JustCoded\DotenvSync\DotenvSync;

$argv = $_SERVER['argv'];

switch(count($argv))
{
	case 0 || 1:
		$dotenvSync = new DotenvSync();
		break;
	case 3:
		$dotenvSync = new DotenvSync($argv[1], $argv[2]);
		break;
}

echo $dotenvSync->sync()->output();

exit($dotenvSync->isSuccess() ? 0 : 1);

